"""Change book-category to many-to-many

Revision ID: eceaa97d0f92
Revises: fffab4c20b9a
Create Date: 2025-04-27 18:19:47.864923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eceaa97d0f92'
down_revision: Union[str, None] = 'fffab4c20b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_category',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'category_id')
    )
    op.drop_constraint('books_category_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_category_id_fkey', 'books', 'categories', ['category_id'], ['id'])
    op.drop_table('book_category')
    # ### end Alembic commands ###
